### PR TITLE
fix tooltip not show in some cases

### LINKED ISSUE #1: Not working with basetable

### PR DESCRIPTION
**Pull request by nihgwu**
close #1

### CODE REVIEW

**Comment by imtmh** [comment]
it is not showing when the hodden character count is 2. it is working if otherwise.

**Comment by nihgwu** [comment]
@imtmh whether to show `...` is decided by the browser, this component doesn't truncate the text, BTW, I tested with 2 characters, it will show `...` if the width is not far from the desired space
image
image

**Comment by imtmh** [comment]
I debugged the issue and found the reason why the tooltip is not shown.

`const isTruncated = !!target && target.scrollWidth > target.offsetWidth`

when the hidden characters count == 2, the scrollWidth and offsetWidth for that particular element is same, still, the text is truncated. Since the above expression output as false, the tooltip is not being shown. @nihgwu any help there?

**Comment by nihgwu** [comment]
Hi @imtmh There is no way to detect the text is truncated by the browser, and I don't think there is any value to show tooltip for 2-character string, you can just set a larger `minWidth` for the column to prevent such a short string being truncated

**Pull request merged**
